### ISSUE TITLE
Define observation space

### ISSUE THREAD

**Issue by genyajoe** [sjsu-interconnect/ourhexgame#1]

**Comment by genyajoe** [comment]
> In the README it implied something like Dict{"observation", "pie_rule_x"}
> where "pie_rule_x" is 1 if pie rule is used and 0 otherwise.
> 
> According to this description, I labeled it "pie_rule_used".
> I opened an issue to modify the observe() method to reflect these changes and noticed a potential discrepancy.
> 
> Are we checking if the pie rule is "used" or are we checking if it is "usable"?
> 
> While this doesn't necessarily change the logical outcome of my changes to issue 1, it does effect how we define observe(), and it does effect the semantics of my changes.

@OwenMastropietro 
I think the obs should show if the rule is being in effect or not by 0/1. 
The action mask should indicate if the pie rule is available or not.

**Comment by pranavi-ch** [comment]
I've reviewed the change, observe is defined correctly now. Can be closed
