### ISSUE TITLE
clean up step() function 

### ISSUE THREAD

**Issue by genyajoe** [sjsu-interconnect/ourhexgame#10]

**Comment by SaiPrakash2k** [comment]
Hey sorry, what is going on with this issue? @francisdavidbustos, @s87217647 are either of you working on this one?

**Comment by francisdavidbustos** [comment]
> Hey sorry, what is going on with this issue? @francisdavidbustos, @s87217647 are either of you working on this one?

I'm just reviewing any changes made. I'll take a look.
