### ISSUE TITLE
Pass whether to use a sparse/dense reward on init method

### ISSUE THREAD

**Issue by ChristoferBerruz** [sjsu-interconnect/ourhexgame#11]
https://github.com/sjsu-interconnect/ourhexgame/blob/0324af1be3bf2cc68603cea8a1e972790ae7b414/ourhexenv.py#L10

Given that the environment can have either a sparse or dense reward, we should also pass the type of reward the environment will be using.

**Comment by NateshReddy** [comment]
I can review this!
