### ISSUE TITLE
pie rule and obs

### ISSUE THREAD

**Issue by genyajoe** [sjsu-interconnect/ourhexgame#29]
If pie_rule_used flag is True,
we need to flip the obs space in the step function.

**Comment by nshah1503** [comment]
I can review

**Comment by genyajoe** [comment]
please review this asap.

**Comment by nshah1503** [comment]
I reviewed it. Couple of things:
- You don't need to manually add pie rule state in the `infos` variable on line #226 and one after, since it's being handled in generateInfo method
-  value of `is_pie_rule_usable` is being changed twice in same loop to same value, line #196

**Comment by KUKREJAANUSHA** [comment]
@genyajoe  Professor, our original implementation handles the pie rule correctly by swapping pieces when activated. Therefore, there is no need to flip the observation space.

**Comment by genyajoe** [comment]
Seems @KUKREJAANUSHA is right. Also, the original implementation should be consistent with the winner check function. 

Swapping: 
https://github.com/sjsu-interconnect/ourhexgame/blob/f5cf6fcef61f0085bb38ce22a62b69024ddc905e/ourhexenv.py#L221
