### ISSUE TITLE
Define the action space

### ISSUE THREAD

**Issue by genyajoe** [sjsu-interconnect/ourhexgame#4]

**Comment by nshah1503** [comment]
i can review

**Comment by nshah1503** [comment]
@genyajoe from the class discussion, I remember that we were talking about making a dynamic action_space, for including pie rule (that is board_size*board_size+1 and then subsequently after first round changing it to dimension of board). I wanted to ask if we're still going with this logic or keeping it static and action masking will take care of pie rule action (i.e terminate the game) ?

**Comment by genyajoe** [comment]
I don't recall the discussion about the dynamic environment. We decided to use action masking with a static action space of size n*n+1.

**Comment by nshah1503** [comment]
@KUKREJAANUSHA I think the action space is defined properly, since we're keeping it static. We can close this issue.

**Comment by s87217647** [comment]
Problem has already been fixed
