### ISSUE TITLE
generate_info does not honor the pie rule in orientation calculation

### ISSUE THREAD

**Issue by ChristoferBerruz** [sjsu-interconnect/ourhexgame#40]
https://github.com/sjsu-interconnect/ourhexgame/blob/10b389593d6e6f1258b61ed327d936d03fe68679/ourhexenv.py#L299

Even tho we agreed that player_1 is red and player_2 is blue, their directions do change after the pie rule. Currently, we are assuming
the direction is constant throughout the game without taking into account whether the pie rule was used. This is a bug.

**Comment by Mayukh747** [comment]
Given the recent discussion in #39, we have decided to stick to an interpretation of the pie rule where the endzones for the players will not be altered. 

Shall we close this issue?

**Comment by ChristoferBerruz** [comment]
That would seem to be the case, we can drop this

**Comment by ChristoferBerruz** [comment]
Closing this issue as we are implementing the pie rule based on https://www.lutanho.net/play/hex.html. We perform a swap and transpose on the stone, without changing the orientation of the players
