### ISSUE TITLE
Dense reward function

### ISSUE THREAD

**Issue by genyajoe** [sjsu-interconnect/ourhexgame#6]

**Comment by GZ72** [comment]
I can review this

**Comment by GZ72** [comment]
@ChristoferBerruz Hi Christor, I think issue 6 is a dense reward function

**Comment by ChristoferBerruz** [comment]
@GZ72 Yes - issue 6 is a dense reward function. Where did you see otherwise? I just "commented" about this issue on Issue #19 because they are related
